# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 386)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 70, 571, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.text_to_send_to_plc = QtWidgets.QTextEdit(Dialog)
        self.text_to_send_to_plc.setGeometry(QtCore.QRect(10, 100, 571, 41))
        self.text_to_send_to_plc.setObjectName("text_to_send_to_plc")
        self.text_readed_from_plc = QtWidgets.QTextEdit(Dialog)
        self.text_readed_from_plc.setGeometry(QtCore.QRect(10, 330, 571, 41))
        self.text_readed_from_plc.setObjectName("text_readed_from_plc")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 571, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_read_from_plc = QtWidgets.QPushButton(Dialog)
        self.pushButton_read_from_plc.setGeometry(QtCore.QRect(10, 300, 571, 23))
        self.pushButton_read_from_plc.setObjectName("pushButton_read_from_plc")
        self.pushButton_send_to_plc = QtWidgets.QPushButton(Dialog)
        self.pushButton_send_to_plc.setGeometry(QtCore.QRect(10, 200, 571, 51))
        self.pushButton_send_to_plc.setObjectName("pushButton_send_to_plc")
        self.label_ns = QtWidgets.QLabel(Dialog)
        self.label_ns.setGeometry(QtCore.QRect(195, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ns.setFont(font)
        self.label_ns.setObjectName("label_ns")
        self.text_ns_var = QtWidgets.QTextEdit(Dialog)
        self.text_ns_var.setGeometry(QtCore.QRect(230, 160, 51, 31))
        self.text_ns_var.setObjectName("text_ns_var")
        self.label_var_id = QtWidgets.QLabel(Dialog)
        self.label_var_id.setGeometry(QtCore.QRect(290, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_var_id.setFont(font)
        self.label_var_id.setObjectName("label_var_id")
        self.text_id_var = QtWidgets.QTextEdit(Dialog)
        self.text_id_var.setGeometry(QtCore.QRect(320, 160, 51, 31))
        self.text_id_var.setObjectName("text_id_var")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(410, 0, 191, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/image001.png"))
        self.label_3.setObjectName("label_3")

        # self.action_invia_al_plc = QtWidgets.QAction(Dialog)
        # self.action_invia_al_plc.setObjectName("action_invia_al_plc")
        # self.action_leggi_da_plc = QtWidgets.QAction(Dialog)
        # self.action_leggi_da_plc.setObjectName("action_leggi_da_plc")

        self.retranslateUi(Dialog)
        self.pushButton_send_to_plc.pressed.connect(self.action_invia_al_plc)
        self.pushButton_read_from_plc.clicked.connect(self.action_leggi_da_plc)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    
    def action_invia_al_plc(self):
        print("pressed")

    def action_leggi_da_plc(self):
        print("clicked")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Test OPCUA"))
        self.label.setText(_translate("Dialog", "Inserisci qui il testo da inviare al PLC"))
        self.label_2.setText(_translate("Dialog", "Visualizzazione del contenuto del buffer del plc"))
        self.pushButton_read_from_plc.setText(_translate("Dialog", "Leggi il buffer del PLC"))
        self.pushButton_send_to_plc.setText(_translate("Dialog", "Invia al PLC"))
        self.label_ns.setText(_translate("Dialog", "ns ="))
        self.label_var_id.setText(_translate("Dialog", "id ="))
        # self.action_invia_al_plc.setText(_translate("Dialog", "_invia_al_plc"))
        # self.action_leggi_da_plc.setText(_translate("Dialog", "_leggi_da_plc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
